"""add_material_access_type

Revision ID: 4e76b84e3062
Revises: e8f9a1b2c3d4
Create Date: 2026-01-18 12:59:45.306125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e76b84e3062'
down_revision: Union[str, None] = 'e8f9a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_translations_id', table_name='translations')
    op.drop_index('ix_translations_language', table_name='translations')
    op.drop_index('ix_translations_lookup', table_name='translations')
    op.drop_index('ix_translations_resource_id', table_name='translations')
    op.drop_index('ix_translations_resource_type', table_name='translations')
    op.drop_table('translations')
    op.drop_index('ix_ui_translations_id', table_name='ui_translations')
    op.drop_index('ix_ui_translations_key', table_name='ui_translations')
    op.drop_index('ix_ui_translations_key_lang', table_name='ui_translations')
    op.drop_index('ix_ui_translations_language', table_name='ui_translations')
    op.drop_table('ui_translations')
    op.alter_column('grades', 'max_score',
               existing_type=sa.INTEGER(),
               nullable=False)
               
    # Create enum type
    conn = op.get_bind()
    # Check if type exists to avoid error if re-running
    # But for simplicity in alembic usually we just create
    sa.Enum('VIEW', 'DOWNLOAD', name='accesstype').create(conn)
    
    op.add_column('material_access', sa.Column('access_type', sa.Enum('VIEW', 'DOWNLOAD', name='accesstype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_access', 'access_type')
    
    # Drop enum type
    conn = op.get_bind()
    sa.Enum('VIEW', 'DOWNLOAD', name='accesstype').drop(conn)
    
    op.alter_column('grades', 'max_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('ui_translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ui_translations_pkey')
    )
    op.create_index('ix_ui_translations_language', 'ui_translations', ['language'], unique=False)
    op.create_index('ix_ui_translations_key_lang', 'ui_translations', ['key', 'language'], unique=True)
    op.create_index('ix_ui_translations_key', 'ui_translations', ['key'], unique=False)
    op.create_index('ix_ui_translations_id', 'ui_translations', ['id'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='translations_pkey')
    )
    op.create_index('ix_translations_resource_type', 'translations', ['resource_type'], unique=False)
    op.create_index('ix_translations_resource_id', 'translations', ['resource_id'], unique=False)
    op.create_index('ix_translations_lookup', 'translations', ['resource_type', 'resource_id', 'field_name', 'language'], unique=True)
    op.create_index('ix_translations_language', 'translations', ['language'], unique=False)
    op.create_index('ix_translations_id', 'translations', ['id'], unique=False)
    # ### end Alembic commands ###
