"""Add Assignment and Submission models

Revision ID: 6b310e4cee90
Revises: fb88d2646ed6
Create Date: 2026-01-11 06:06:27.575062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b310e4cee90'
down_revision: Union[str, None] = 'fb88d2646ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
