"""Add director_name and capacity to School model

Revision ID: 7d2025b5a2a7
Revises: 09c05bc61345
Create Date: 2026-01-10 05:42:20.871365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2025b5a2a7'
down_revision: Union[str, None] = '09c05bc61345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('director_name', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'capacity')
    op.drop_column('schools', 'director_name')
    # ### end Alembic commands ###
