"""Add Attendance and Grade models

Revision ID: c21a31f2822f
Revises: 7d2025b5a2a7
Create Date: 2026-01-11 05:58:18.139336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21a31f2822f'
down_revision: Union[str, None] = '7d2025b5a2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
