"""Add LessonSession and StudentNote models

Revision ID: d17b85470b0f
Revises: 6b310e4cee90
Create Date: 2026-01-11 06:49:52.133638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17b85470b0f'
down_revision: Union[str, None] = '6b310e4cee90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
