"""Add TimeSlot and Schedule models

Revision ID: fb88d2646ed6
Revises: c21a31f2822f
Create Date: 2026-01-11 06:03:01.097170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb88d2646ed6'
down_revision: Union[str, None] = 'c21a31f2822f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
