"""
AI Performance Analysis models for identifying student weaknesses and generating improvement plans.
"""
from datetime import datetime
from typing import Optional, List, Dict
from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, JSON, Text
from sqlalchemy.orm import relationship

from app.core.database import Base


class AIPerformanceAnalysis(Base):
    """
    Stores AI-generated analysis of student performance.
    Identifies weak topics based on exam/assignment results.
    """
    __tablename__ = "ai_performance_analysis"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    subject_id = Column(Integer, ForeignKey("subjects.id"), nullable=False, index=True)
    
    # Analysis metadata
    analysis_date = Column(DateTime, default=datetime.utcnow, nullable=False)
    data_period_start = Column(DateTime, nullable=False)  # Period of data analyzed
    data_period_end = Column(DateTime, nullable=False)
    
    # AI Analysis Results (JSON format)
    weak_topics = Column(JSON, nullable=False)  # [{"topic": "Algebra", "confidence": 0.85, "severity": "high"}]
    strong_topics = Column(JSON)  # [{"topic": "Geometry", "confidence": 0.92}]
    confidence_scores = Column(JSON)  # {"overall": 0.78, "by_topic": {...}}
    
    # Performance metrics
    overall_performance_score = Column(Float)  # 0-100
    performance_trend = Column(String(20))  # "improving", "declining", "stable"
    at_risk_level = Column(String(20))  # "low", "medium", "high", "critical"
    
    # Recommendations
    recommended_actions = Column(JSON)  # [{"action": "practice", "topic": "...", "priority": 1}]
    estimated_improvement_time = Column(Integer)  # Days to improve
    
    # Relationships
    student = relationship("User", foreign_keys=[student_id])
    subject = relationship("Subject")
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class AIImprovementPlan(Base):
    """
    Personalized improvement plan generated by AI for struggling students.
    """
    __tablename__ = "ai_improvement_plans"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    subject_id = Column(Integer, ForeignKey("subjects.id"), nullable=False, index=True)
    analysis_id = Column(Integer, ForeignKey("ai_performance_analysis.id"), nullable=True)
    
    # Plan details
    title = Column(String(255), nullable=False)
    description = Column(Text)
    
    # Weak topics to focus on (JSON array)
    weak_topics = Column(JSON, nullable=False)  # [{"topic": "...", "priority": 1, "current_score": 45}]
    
    # Recommended resources (JSON array)
    recommended_resources = Column(JSON)  # [{"type": "textbook", "id": 123, "chapter": 5}]
    
    # Practice exercises (JSON array)
    practice_exercises = Column(JSON)  # [{"topic": "...", "difficulty": "easy", "count": 10}]
    
    # Goals and tracking
    target_completion_date = Column(DateTime)
    target_improvement_percentage = Column(Float)  # e.g., 20% improvement
    
    # Progress tracking (JSON)
    progress_tracking = Column(JSON, default={})  # {"completed_exercises": 5, "current_score": 55}
    
    # Status
    status = Column(String(20), default="active")  # "active", "completed", "abandoned"
    completion_percentage = Column(Float, default=0.0)
    
    # Relationships
    student = relationship("User", foreign_keys=[student_id])
    subject = relationship("Subject")
    analysis = relationship("AIPerformanceAnalysis", foreign_keys=[analysis_id])
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)


class AITutorSession(Base):
    """
    Stores AI tutor chat sessions for students asking homework questions.
    """
    __tablename__ = "ai_tutor_sessions"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    subject_id = Column(Integer, ForeignKey("subjects.id"), nullable=True, index=True)
    
    # Session metadata
    started_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    ended_at = Column(DateTime, nullable=True)
    session_duration_seconds = Column(Integer)
    
    # Chat messages (JSON array)
    messages = Column(JSON, default=[])  # [{"role": "user/assistant", "content": "...", "timestamp": "..."}]
    
    # Topics discussed (extracted by AI)
    topics_discussed = Column(JSON)  # ["Quadratic Equations", "Factoring"]
    
    # Problems solved
    problems_solved = Column(Integer, default=0)
    problems_attempted = Column(Integer, default=0)
    
    # Feedback
    student_rating = Column(Integer, nullable=True)  # 1-5 stars
    was_helpful = Column(String(20), nullable=True)  # "yes", "no", "somewhat"
    
    # Relationships
    student = relationship("User", foreign_keys=[student_id])
    subject = relationship("Subject")
    
    created_at = Column(DateTime, default=datetime.utcnow)


class AIGeneratedPractice(Base):
    """
    AI-generated practice problems for students based on weak topics.
    """
    __tablename__ = "ai_generated_practice"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    subject_id = Column(Integer, ForeignKey("subjects.id"), nullable=False, index=True)
    improvement_plan_id = Column(Integer, ForeignKey("ai_improvement_plans.id"), nullable=True)
    
    # Problem details
    topic = Column(String(255), nullable=False, index=True)
    difficulty_level = Column(String(20), nullable=False)  # "easy", "medium", "hard"
    
    # Problem content
    problem_text = Column(Text, nullable=False)
    problem_type = Column(String(50))  # "multiple_choice", "short_answer", "essay", "code"
    options = Column(JSON, nullable=True)  # For multiple choice: ["A", "B", "C", "D"]
    
    # Solution
    correct_answer = Column(Text, nullable=False)
    explanation = Column(Text)  # Step-by-step solution
    hints = Column(JSON)  # Progressive hints: ["hint1", "hint2", ...]
    
    # Student response
    student_answer = Column(Text, nullable=True)
    is_correct = Column(String(20), nullable=True)  # "correct", "incorrect", "partial"
    attempts_count = Column(Integer, default=0)
    time_spent_seconds = Column(Integer, nullable=True)
    
    # Metadata
    generated_at = Column(DateTime, default=datetime.utcnow)
    answered_at = Column(DateTime, nullable=True)
    
    # Relationships
    student = relationship("User", foreign_keys=[student_id])
    subject = relationship("Subject")
    improvement_plan = relationship("AIImprovementPlan", foreign_keys=[improvement_plan_id])
    
    created_at = Column(DateTime, default=datetime.utcnow)
